# Generated by Django 4.1.7 on 2023-05-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carinfo',
            fields=[
                ('carId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=200)),
                ('carImages', models.CharField(max_length=2000)),
                ('fuleType', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('trasmission', models.CharField(max_length=100)),
                ('carRent', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('carType', models.CharField(max_length=200)),
            ],
        ),
    ]
