# Generated by Django 4.1.7 on 2023-05-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='carId',
            new_name='id',
        ),
    ]
